### ISSUE TITLE
Add kedro-grpc-server example

### ISSUE THREAD

**Issue by mmchougule** [quantumblacklabs/kedro-community#68]
## Description
Would this be a better place to have a link to an example of using Kedro gRPC Server? If so then I can add the links to the README and create a PR. :) I have examples in Scala, Go, Python, and Node so far for triggering kedro pipelines. 

## Context
Would love to show an example of the kedro gRPC server plugin.

## Possible Implementation
https://github.com/mmchougule/kedro-grpc-scala-client/
https://github.com/mmchougule/kedro-grpc-go-client/
https://github.com/mmchougule/kedro-grpc-node-client/

**Comment by laisbsc** [comment]
Hey there @mmchougule!

Yes, this is the place for Kedro-examples! You can add them to the list of Community maintained projects with a brief description. We will be happy to have it there.

Thanks a million for contributing 😄
